let titles = {
    'accordion-bulk-open': 'Eksempel på accordion med åbn/luk alle',
    'accordion-error': 'Eksempel på accordion med fejl',
    'accordion-success': 'Eksempel på accordion med succesbesked',
    'accordion': 'Eksempel på accordion',
    'alert-close': 'Eksempel på besked med luk knap',
    'alert-error': 'Eksempel på fejlbesked',
    'alert-info': 'Eksempel på informativ besked',
    'alert-paragraph': 'Eksempel på besked med paragrafbredde',
    'alert-success': 'Eksempel på succesbesked',
    'alert-warning': 'Eksempel på besked med advarsel',
    'alerts-texts': 'Eksempel på besked i forskellige formater',
    'alerts': 'Eksempel på beskeder',
    'anchorlinks': 'Eksempel på anchorlinks',
    'back-link': 'Eksempel på tilbage-link',
    'back-to-top': 'Eksempel på tilbage til toppen',
    'badges-status': 'Eksempel på statusbadges',
    'badges': 'Eksempel på badges',
    'border-radius': 'Eksempel på firkantede og runde hjørner',
    'borders': 'Eksempel på streger',
    'breadcrumbs': 'Eksempel på brødkrumme',
    'button-primary': 'Eksempel på knap',
    'buttons-back': 'Eksempel på tilbageknap',
    'buttons-only-icon': 'Eksempel på klikbart ikon',
    'buttons-primary': 'Eksempel på primærknap',
    'buttons-secondary': 'Eksempel på sekundærknap',
    'buttons-tertiary': 'Eksempel på tertiærknap',
    'buttons-with-icon': 'Eksempel på knap med ikon',
    'caption': 'Eksempel på billedtekst',
    'card': 'Eksempel på card',
    'cards-full-width': 'Eksempel på card med billede',
    'cards-half-width': 'Eksempel på cards i to kolonner',
    'cards-same-height': 'Eksempel på cards med samme højde',
    'cards-third-width': 'Eksempel på cards i tre kolonner',
    'checkbox-collapse': 'Eksempel på tjekboks med skjult indhold',
    'checkbox-group-helptext': 'Eksempel på tjekboksgruppe med hjælpetekst',
    'checkbox-helptext': 'Eksempel på tjekbokse med hjælpetekst',
    'checkbox-large': 'Eksempel på tjekbokse',
    'cookie-message': 'Eksempel på cookiemeddelelse',
    'date-input': 'Eksempel på datofelter',
    'date-picker-default-date': 'Eksempel på datovælger med fast værdi',
    'date-picker-error': 'Eksempel på datovælger med fejlmeddelelse',
    'date-picker-format': 'Eksempel på datovælger med andet datoformat',
    'date-picker-interval': 'Eksempel på datovælger med begrænsede datoer',
    'date-picker': 'Eksempel på datovælger',
    'details': 'Eksempel på detaljer',
    'displaytext': 'Eksempel på stor tekst',
    'error-message-accordion': 'Eksempel på accordion med fejl',
    'error-message-checkbox': 'Eksempel på tjekbokse med fejlmeddelelse',
    'error-message-date': 'Eksempel på datofelter med fejlmeddelelse',
    'error-message-definition': 'Eksempel på fejlmeddelelsetekst',
    'error-message-file-input': 'Eksempel på vedhæft fil med fejlmeddelelse',
    'error-message-name': 'Eksempel på inputfelt med fejlmeddelelse',
    'error-message-radio': 'Eksempel på radioknapper med fejlmeddelelse',
    'error-message': 'Eksempel på fejlmeddelelse',
    'error-summary-page': 'Eksempel på placering af fejlopsummering',
    'error-summary': 'Eksempel på fejlopsummering',
    'external-link': 'Eksempel på eksternt link',
    'fds-base-svg': 'Ikonsamling (kan ses i browserkonsollen)',
    'fieldset-complex': 'Eksempel på kompleks formularstruktur',
    'fieldset': 'Eksempel på formularstruktur',
    'file-input': 'Eksempel på vedhæft fil',
    'font-preload': 'font-preload',
    'footer-complex': 'Eksempel på kompleks footer',
    'footer-four-columns-language': 'Eksempel på sprogvælger i en kompleks footer',
    'footer-four-columns': 'Eksempel på footer med fire kolonner',
    'footer-logo': 'Eksempel på footer med logo',
    'footer-simple-language': 'Eksempel på sprogvælger i en simpel footer',
    'footer-simple': 'Eksempel på footer',
    'footer-three-columns': 'Eksempel på footer med tre kolonner',
    'function-link-download': 'Eksempel på funktionslink til download',
    'function-link-gem': 'Eksempel på funktionslink til at gemme en kladde',
    'function-link-luk': 'Eksempel på funktionslink til luk',
    'function-link-print': 'Eksempel på funktionslink til print',
    'function-link-slet': 'Eksempel på funktionslink til sletning',
    'grid--all-breakpoints': 'Eksempel på grid med alle breakpoints',
    'grid--column-wrapping': 'Eksempel på grid med kolonneombrydning',
    'grid--mix-match': 'Eksempel på grid med forskellige kolonneklasser',
    'grid--nesting': 'Eksempel på grid med indlejring af rækker med kolonner',
    'grid--no-gutters': 'Eksempel på grid uden afstand mellem kolonner',
    'grid--offsets-reset': 'Eksempel på grid med nulstilling af forskydning af kolonne',
    'grid--offsets': 'Eksempel på grid med forskydning af kolonner',
    'grid--one-column-width': 'Eksempel på grid med fast bredde på én kolonne',
    'grid--ordering-visual': 'Eksempel på grid med ændring af rækkefølgen på kolonner',
    'grid--stacked-horizontal': 'Eksempel på grid med stablede kolonner til kolonner på række',
    'grid--util-flex-horizontal-align': 'Eksempel på grid med horisontal alignment af kolonner',
    'grid--util-flex-vertical-align-01': 'Eksempel på grid med vertikal alignment af kolonner',
    'grid--util-flex-vertical-align-02': 'Eksempel på grid med vertikal alignment af kolonner på samme række',
    'grid--util-margin': 'Eksempel på grid med indryk af kolonner',
    'grid-simple': 'Eksempel på grid',
    'header-menu-top': 'header-menu-top',
    'header-navigation-mobile': 'header-navigation-mobile',
    'header-navigation': 'header-navigation',
    'header-overview': 'header-overview',
    'header-portal-mobile': 'header-portal-mobile',
    'header-portal': 'header-portal',
    'header-simple': 'Eksempel på simpel header',
    'header-solution-mobile': 'header-solution-mobile',
    'header-solution': 'header-solution',
    'header-switch-language': 'Eksempel på header med sprogvælger',
    'header-with-navigation': 'Eksempel på header med navigation og søgefelt',
    'heading': 'Eksempel på en overskrift, der ligner et andet niveau',
    'headings': 'Overskriftsstruktur',
    'helptext': 'Eksempel på hjælpetekst',
    'icon-class': 'Eksempel på ikon indsat med klasse',
    'icon': 'Eksempel på ikon',
    'icons--svg': 'Eksempel på ikoner',
    'ikon-samling': 'Ikonsamling',
    'inlinetext': 'Eksempel på brødtekst',
    'kontaktoplysninger-hentet': 'Eksempel på inputfelt med hentet data',
    'language-switcher-tooltip': 'Eksempel på sprogvælger med tooltip',
    'language-switcher': 'Eksempel på sprogvælger',
    'lead_paragraph': 'Eksempel på manchet',
    'line_length': 'Eksempel på linjelængde',
    'line_spacing': 'Eksempel på linjeafstand',
    'links': 'Eksempel på links',
    'lists-ordered': 'Eksempel på tegnopstilling',
    'lists-unordered': 'Eksempel på punktopstilling',
    'lists': 'Eksempel på lister',
    'logget-af': 'logget-af',
    'modal-forced-action': 'Eksempel på modal, som kræver handling',
    'modal': 'Eksempel på modal',
    'overflow-menu': 'Eksempel på overflow menu',
    'pagination-long': 'Eksempel på paginering med 12 sider',
    'pagination-short': 'Eksempel på paginering med 7 sider',
    'pagination': 'Eksempel på paginering',
    'radio-collapse': 'Eksempel på radioknapper med skjult indhold',
    'radiobutton-group-helptext': 'Eksempel på radioknapgruppe med hjælpetekst',
    'radiobutton-helptext': 'Eksempel på radioknapper med hjælpetekst',
    'radiobutton': 'Eksempel på radioknapper',
    'search': 'Eksempel på søgefelt',
    'secondary-links': 'Eksempel på sekundært link',
    'select-error': 'Eksempel på dropdown med fejlmeddelelse',
    'select': 'Eksempel på dropdown',
    'session-udloeber-aendringer-gemt': 'Eksempel på session udløb med gemte ændringer',
    'session-udloeber-aendringer-ikke-gemt': 'Eksempel på session udløb med ændringer der ikke er gemt',
    'session-udloeber': 'Eksempel på sessionudløb',
    'shadows': 'Eksempel på skygger',
    'sidenav-information-level1': 'Eksempel på venstremenu med information',
    'sidenav-normal-level1': 'Eksempel på venstremenu med ét niveau',
    'sidenav-normal-level2': 'Eksempel på venstremenu med to niveauer',
    'sidenav-normal-level3': 'Eksempel på venstremenu med tre niveauer',
    'simple-base-svg': 'Uddrag af ikonsamlingen',
    'skip-link-eksempel': 'Eksempel på skip-link',
    'skiplink': 'Eksempel på skip-link',
    'solutionheading': 'Eksempel på løsningstitel i header',
    'sort': 'Eksempel på sortering med overflowmenu',
    'spinner': 'Eksempel på spinner',
    'structured-list--edit': 'Eksempel på struktureret liste med redigérlink',
    'structured-list': 'Eksempel på struktureret liste',
    'subheading': 'Eksempel på subheading',
    'switch-language-mobile': 'switch-language-mobile',
    'switch-language': 'switch-language',
    'table--bordered-zebra': 'Eksempel på tabel med zebralinjer',
    'table--borderless': 'Eksempel på tabel uden ramme',
    'table--lineheight': 'Eksempel på tabeller med forskellig linjehøjde',
    'table--responsive': 'Eksempel på responsiv tabel',
    'table-pagination': 'Eksempel på tabel med paginering',
    'table-search': 'Eksempel på søgning i tabel',
    'table-selectable-functions': 'Eksempel på valgbare rækker i en tabel med funktionsknapper',
    'table-selectable': 'Eksempel på valgbare rækker i en tabel',
    'table-sort': 'Eksempel på sortering i tabel',
    'table': 'Eksempel på tabel',
    'tabs-icons': 'Eksempel på faneblade med ikoner',
    'tabs-navigation': 'Eksempel på faneblade til navigation',
    'tabs': 'Eksempel på faneblade',
    'tags-icon': 'Eksempel på tags med luk-ikon',
    'tags': 'Eksempel på tags',
    'telefonnummer-dansk-fejl': 'Eksempel på angivelse af dansk telefonnummer med fejlbesked',
    'telefonnummer-dansk': 'Eksempel på angivelse af dansk telefonnummer',
    'telefonnummer-fejl-uden-landekode': 'Eksempel på angivelse af telefonnummer med udenlandsk nummer uden landekode',
    'telefonnummer-udenlandsk-ugyldigt': 'Eksempel på angivelse af ugyldigt telefonnummer',
    'telefonnummer-udenlandsk': 'Eksempel på angivelse af udenlandsk telefonnummer',
    'telefonnummer': 'Eksempel på angivelse af telefonnummer',
    'text-area-character-limit-error': 'Eksempel på inputfelt med karakterbegrænsning og fejlmeddelelse',
    'text-area-character-limit': 'Eksempel på tekstområde med karakterbegrænsning',
    'text-area-error': 'Eksempel på tekstområde med fejlmeddelelse',
    'text-area': 'Eksempel på tekstområde',
    'text-input-autocomplete': 'Eksempel på brug af autocomplete-attributten',
    'text-input-character-limit-error': 'Eksempel på inputfelt med karakterbegrænsning og fejlmeddelelse',
    'text-input-character-limit': 'Eksempel på inputfelt med karakterbegrænsning',
    'text-input-disabled': 'Eksempel på deaktiveret inputfelt',
    'text-input-helptext': 'Eksempel på inputfelt med hjælpetekst',
    'text-input-mandatory': 'Eksempel på formular med flest obligatoriske inputfelter',
    'text-input-optional': 'Eksempel på formular med flest frivillige inputfelter',
    'text-input-prefix-suffix': 'Eksempel på inputfelter med prefix og suffix',
    'text-input-readonly': 'Eksempel på readonly inputfelt',
    'text-input-suffix-error': 'Eksempel på inputfelt med suffix og fejlmeddelelse',
    'text-input-width': 'Eksempel på inputfelter med forskellig bredde',
    'text-input': 'Eksempel på inputfelt',
    'toastbesked-error': 'Eksempel på toastbesked med fejl',
    'toastbesked-info': 'Eksempel på toastbesked med information',
    'toastbesked-onlyheading': 'Eksempel på toastbesked uden brødtekst',
    'toastbesked-success': 'Eksempel på toastbesked med succes',
    'toastbesked-warning': 'Eksempel på toastbesked med advarsel',
    'toastbesked': 'Eksempel på toastbesked',
    'toggle': 'Eksempel på toggle switch',
    'tooltip-checkbox': 'Eksempel på tjekboks med tooltip',
    'tooltip-helpicon': 'Eksempel på ikon med tooltip',
    'tooltip-hover-button': 'Eksempel på knap med hover-tooltip',
    'tooltip-iconbutton': 'Eksempel på ikon med hover-tooltip',
    'tooltip-position': 'Eksempel på placering af tooltip',
    'tooltip-radiobuttons': 'Eksempel på radioknap med tooltip',
    'tooltip-text': 'Eksempel på brødtekst med tooltip',
    'tooltip-textinput': 'Eksempel på inputfelt med tooltip',
    'tringuide-clickable': 'Eksempel på synlig trinindikator',
    'tringuide-error-responsive': 'Eksempel på trinindikator med fejl',
    'tringuide-information': 'Eksempel på trinindikator med information',
    'tringuide-locked': 'Eksempel på trinindikator med låste trin',
    'tringuide-overflowmenu': 'Eksempel på trinindikator i overflow menu',
    'tringuide-responsive-overflowmenu': 'Eksempel på responsiv trinindikator',
    'virksomhedsoplysninger': 'Eksempel på formular med hentet data',
    'when-bike-desktop': 'Eksempel på responsiv infografik på desktop fuld bredde',
    'when-bike-phone': 'Eksempel på responsiv infografik på mobil',
    'when-bike-responsive': 'Eksempel på responsiv infografik',
    'when-bike-tablet': 'Eksempel på responsiv infografik på tablet'
};

exports.default = titles;