let titles = {
    'accordion-bulk-open': 'Eksempel på accordion med åbn/luk alle',
    'accordion-error': 'Eksempel på accordion med fejl',
    'accordion-success': 'Eksempel på accordion med succesbesked',
    'accordion': 'Eksempel på accordion',
    'alert-close': 'Eksempel på besked med luk knap',
    'alert-error': 'Eksempel på fejlbesked',
    'alert-info': 'Eksempel på informativ besked',
    'alert-paragraph': 'Eksempel på besked med paragrafbredde',
    'alert-success': 'Eksempel på succesbesked',
    'alert-warning': 'Eksempel på besked med advarsel',
    'alerts-texts': 'Eksempel på besked i forskellige formater',
    'alerts': 'Eksempel på beskeder',
    'anchorlinks': 'Eksempel på anchorlinks',
    'back-link': 'Eksempel på tilbage-link',
    'back-to-top': 'Eksempel på tilbage til toppen',
    'badges-status': 'Eksempel på statusbadges',
    'badges': 'Eksempel på badges',
    'border-radius': 'Eksempel på firkantede og runde hjørner',
    'borders': 'Eksempel på streger',
    'breadcrumbs': 'Eksempel på brødkrumme',
    'button-primary': 'Eksempel på primærknap',
    'buttons-back': 'Eksempel på tilbageknap',
    'buttons-only-icon': 'Eksempel på knap som ikon',
    'buttons-primary': 'Eksempel på primærknap i forskellige stadier',
    'buttons-secondary': 'Eksempel på sekundærknap',
    'buttons-tertiary': 'Eksempel på tertiær knap',
    'buttons-with-icon': 'Eksempel på knap med ikon',
    'caption': 'Eksempel på billedtekst',
    'card': 'Eksempel på card',
    'cards-full-width': 'Eksempel på card med billede',
    'cards-half-width': 'Eksempel på cards i to kolonner',
    'cards-same-height': 'Eksempel på cards med samme højde',
    'cards-third-width': 'Eksempel på cards i tre kolonner',
    'checkbox-collapse': 'Eksempel på tjekboks med skjult indhold',
    'checkbox-group-helptext': 'Eksempel på tjekboksgruppe med hjælpetekst',
    'checkbox-helptext': 'Eksempel på tjekbokse med hjælpetekst',
    'checkbox-large': 'Eksempel på tjekbokse',
    'cookie-message': 'Eksempel på cookiemeddelelse',
    'date-input': 'Eksempel på datofelter',
    'date-picker-default-date': 'Eksempel på datovælger med fast værdi',
    'date-picker-error': 'Eksempel på datovælger med fejlmeddelelse',
    'date-picker-format': 'Eksempel på datovælger med andet datoformat',
    'date-picker-interval': 'Eksempel på datovælger med begrænsning',
    'date-picker': 'Eksempel på datovælger',
    'details': 'Eksempel på skjul og vis af indhold',
    'displaytext': 'Eksempel på stor tekst',
    'error-message-accordion': 'Eksempel på accordion med fejl',
    'error-message-checkbox': 'Eksempel på tjekbokse med fejlmeddelelse',
    'error-message-date': 'Eksempel på datofelter med fejlmeddelelse',
    'error-message-definition': 'Eksempel på fejlmeddelelsetekst',
    'error-message-file-input': 'Eksempel på felt til vedhæftning af fil med fejlmeddelelse',
    'error-message-name': 'Eksempel på tekstfelt med fejlmeddelelse',
    'error-message-radio': 'Eksempel på radioknapper med fejlmeddelelse',
    'error-message': 'Eksempel på fejlmeddelelse',
    'error-summary-page': 'Eksempel på placering af fejlopsummering',
    'error-summary': 'Eksempel på fejlopsummering',
    'external-link': 'Eksempel på eksternt link',
    'fds-base-svg': 'Ikonsamling (kan ses i browserkonsollen)',
    'fieldset-complex': 'fieldset-complex',
    'fieldset': 'fieldset',
    'file-input': 'file-input',
    'font-preload': 'font-preload',
    'footer-complex': 'footer-complex',
    'footer-four-columns-language': 'footer-four-columns-language',
    'footer-four-columns': 'footer-four-columns',
    'footer-logo': 'footer-logo',
    'footer-simple-language': 'footer-simple-language',
    'footer-simple': 'footer-simple',
    'footer-three-columns': 'footer-three-columns',
    'function-link-download': 'function-link-download',
    'function-link-gem': 'function-link-gem',
    'function-link-luk': 'function-link-luk',
    'function-link-print': 'function-link-print',
    'function-link-slet': 'function-link-slet',
    'grid--all-breakpoints': 'grid--all-breakpoints',
    'grid--column-wrapping': 'grid--column-wrapping',
    'grid--mix-match': 'grid--mix-match',
    'grid--nesting': 'grid--nesting',
    'grid--no-gutters': 'grid--no-gutters',
    'grid--offsets-reset': 'grid--offsets-reset',
    'grid--offsets': 'grid--offsets',
    'grid--one-column-width': 'grid--one-column-width',
    'grid--ordering-visual': 'grid--ordering-visual',
    'grid--stacked-horizontal': 'grid--stacked-horizontal',
    'grid--util-flex-horizontal-align': 'grid--util-flex-horizontal-align',
    'grid--util-flex-vertical-align-01': 'grid--util-flex-vertical-align-01',
    'grid--util-flex-vertical-align-02': 'grid--util-flex-vertical-align-02',
    'grid--util-margin': 'grid--util-margin',
    'grid-simple': 'grid-simple',
    'header-menu-top': 'header-menu-top',
    'header-navigation-mobile': 'header-navigation-mobile',
    'header-navigation': 'header-navigation',
    'header-overview': 'header-overview',
    'header-portal-mobile': 'header-portal-mobile',
    'header-portal': 'header-portal',
    'header-simple': 'header-simple',
    'header-solution-mobile': 'header-solution-mobile',
    'header-solution': 'header-solution',
    'header-switch-language': 'header-switch-language',
    'header-with-navigation': 'header-with-navigation',
    'heading': 'heading',
    'headings': 'headings',
    'helptext': 'helptext',
    'icon-class': 'icon-class',
    'icon': 'icon',
    'icons--svg': 'icons--svg',
    'ikon-samling': 'ikon-samling',
    'inlinetext': 'inlinetext',
    'kontaktoplysninger-hentet': 'kontaktoplysninger-hentet',
    'language-switcher-tooltip': 'language-switcher-tooltip',
    'language-switcher': 'language-switcher',
    'lead_paragraph': 'lead_paragraph',
    'line_length': 'line_length',
    'line_spacing': 'line_spacing',
    'links': 'links',
    'lists-ordered': 'lists-ordered',
    'lists-unordered': 'lists-unordered',
    'lists': 'lists',
    'logget-af': 'logget-af',
    'modal-forced-action': 'modal-forced-action',
    'modal': 'modal',
    'overflow-menu': 'overflow-menu',
    'pagination-long': 'pagination-long',
    'pagination-short': 'pagination-short',
    'pagination': 'pagination',
    'radio-collapse': 'radio-collapse',
    'radiobutton-group-helptext': 'radiobutton-group-helptext',
    'radiobutton-helptext': 'radiobutton-helptext',
    'radiobutton': 'radiobutton',
    'search': 'search',
    'secondary-links': 'secondary-links',
    'select-error': 'select-error',
    'select': 'select',
    'session-udloeber-aendringer-gemt': 'session-udloeber-aendringer-gemt',
    'session-udloeber-aendringer-ikke-gemt': 'session-udloeber-aendringer-ikke-gemt',
    'session-udloeber': 'session-udloeber',
    'shadows': 'shadows',
    'sidenav-information-level1': 'sidenav-information-level1',
    'sidenav-normal-level1': 'sidenav-normal-level1',
    'sidenav-normal-level2': 'sidenav-normal-level2',
    'sidenav-normal-level3': 'sidenav-normal-level3',
    'simple-base-svg': 'simple-base-svg',
    'skip-link-eksempel': 'skip-link-eksempel',
    'skiplink': 'skiplink',
    'solutionheading': 'solutionheading',
    'sort': 'sort',
    'spinner': 'spinner',
    'structured-list--edit': 'structured-list--edit',
    'structured-list': 'structured-list',
    'subheading': 'subheading',
    'switch-language-mobile': 'switch-language-mobile',
    'switch-language': 'switch-language',
    'table--bordered-zebra': 'table--bordered-zebra',
    'table--borderless': 'table--borderless',
    'table--lineheight': 'table--lineheight',
    'table--responsive': 'table--responsive',
    'table-pagination': 'table-pagination',
    'table-search': 'table-search',
    'table-selectable-functions': 'table-selectable-functions',
    'table-selectable': 'table-selectable',
    'table-sort': 'table-sort',
    'table': 'table',
    'tabs-icons': 'tabs-icons',
    'tabs-navigation': 'tabs-navigation',
    'tabs': 'tabs',
    'tags-icon': 'tags-icon',
    'tags': 'tags',
    'telefonnummer-dansk-fejl': 'telefonnummer-dansk-fejl',
    'telefonnummer-dansk': 'telefonnummer-dansk',
    'telefonnummer-fejl-uden-landekode': 'telefonnummer-fejl-uden-landekode',
    'telefonnummer-udenlandsk-ugyldigt': 'telefonnummer-udenlandsk-ugyldigt',
    'telefonnummer-udenlandsk': 'telefonnummer-udenlandsk',
    'telefonnummer': 'telefonnummer',
    'text-area-character-limit-error': 'text-area-character-limit-error',
    'text-area-character-limit': 'text-area-character-limit',
    'text-area-error': 'text-area-error',
    'text-area': 'text-area',
    'text-input-autocomplete': 'text-input-autocomplete',
    'text-input-character-limit-error': 'text-input-character-limit-error',
    'text-input-character-limit': 'text-input-character-limit',
    'text-input-disabled': 'text-input-disabled',
    'text-input-helptext': 'text-input-helptext',
    'text-input-mandatory': 'text-input-mandatory',
    'text-input-optional': 'text-input-optional',
    'text-input-prefix-suffix': 'text-input-prefix-suffix',
    'text-input-readonly': 'text-input-readonly',
    'text-input-suffix-error': 'text-input-suffix-error',
    'text-input-width': 'text-input-width',
    'text-input': 'text-input',
    'toastbesked-error': 'toastbesked-error',
    'toastbesked-info': 'toastbesked-info',
    'toastbesked-onlyheading': 'toastbesked-onlyheading',
    'toastbesked-success': 'toastbesked-success',
    'toastbesked-warning': 'toastbesked-warning',
    'toastbesked': 'toastbesked',
    'toggle': 'toggle',
    'tooltip-checkbox': 'tooltip-checkbox',
    'tooltip-helpicon': 'tooltip-helpicon',
    'tooltip-hover-button': 'tooltip-hover-button',
    'tooltip-iconbutton': 'tooltip-iconbutton',
    'tooltip-position': 'tooltip-position',
    'tooltip-radiobuttons': 'tooltip-radiobuttons',
    'tooltip-text': 'tooltip-text',
    'tooltip-textinput': 'tooltip-textinput',
    'tringuide-clickable': 'tringuide-clickable',
    'tringuide-error-responsive': 'tringuide-error-responsive',
    'tringuide-information': 'tringuide-information',
    'tringuide-locked': 'tringuide-locked',
    'tringuide-overflowmenu': 'tringuide-overflowmenu',
    'tringuide-responsive-overflowmenu': 'tringuide-responsive-overflowmenu',
    'virksomhedsoplysninger': 'virksomhedsoplysninger',
    'when-bike-desktop': 'when-bike-desktop',
    'when-bike-phone': 'when-bike-phone',
    'when-bike-responsive': 'when-bike-responsive',
    'when-bike-tablet': 'when-bike-tablet'
};

exports.default = titles;